version: '3'
services:
  react-app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=martin
      - CHOKIDAR_USEPOLLING=true
      - PUBLIC_URL=http://localhost:3001
    networks:
      - santos-app-network
      
networks:
  santos-app-network:
    external: true